# Site settings
title: hackers.org.br
description: > # this means to ignore newlines until "baseurl:"
  Site principal da organização hackers.org.br
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hackers.org.br" # the base hostname & protocol for your site
github_username: hackersbr

# Build settings
markdown: kramdown
